# Generated by Django 3.0 on 2019-12-12 13:21

from django.db import migrations, models
import django_enum_choices.choice_builders
import django_enum_choices.fields
import reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('created_at_img', models.DateTimeField(auto_now=True, verbose_name='Image created at')),
                ('image', models.ImageField(blank=True, null=True, upload_to=reports.models.image_direcotry_path_uuid)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('status', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Waiting Confirmation', 'Waiting Confirmation'), ('Confirmed', 'Confirmed'), ('Cleaned', 'Cleaned'), ('Wont Clean', 'Wont Clean')], default=reports.models.Status['WAITING_CONFIRMATION'], enum_class=reports.models.Status, max_length=20)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': '',
                'ordering': ('-created_at',),
                'managed': True,
            },
        ),
    ]
