# Generated by Django 2.2.7 on 2019-11-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportModel',
            new_name='Report',
        ),
    ]
