# Generated by Django 3.0 on 2019-12-12 16:15

from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=django_enum_choices.fields.EnumChoiceField(blank=True, choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Waiting Confirmation', 'Waiting Confirmation'), ('Confirmed', 'Confirmed'), ('Cleaned', 'Cleaned'), ('Wont Clean', 'Wont Clean')], default=reports.models.Status['WAITING_CONFIRMATION'], enum_class=reports.models.Status, max_length=20),
        ),
    ]
