# Generated by Django 2.2.7 on 2019-11-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20191114_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_at_img',
            field=models.DateTimeField(auto_now=True, verbose_name='Image created at'),
        ),
    ]
