# Generated by Django 3.0 on 2019-12-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20191119_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
    ]
